### ISSUE TITLE
License

### ISSUE THREAD

**Issue by krypt-n** [pasuder/hokuyo-java-lib#1]
Since this code is on github, I assume that you'd allow other people to use it.

Could you add a License? (Or tell me where I can find it, in case I missed it).

**Comment by pasuder** [comment]
OK. I will add it. Code was based on something other tool. I need to check it if there was some licences.

**Comment by pasuder** [comment]
I have checked. Code has been based on code created by @greenwing. I found only one repository which contains whole code which has been written by him: https://github.com/grunendrache/hokuyo-comm. There is no license.

**Comment by krypt-n** [comment]
Okay, thanks for the info.

**Comment by pasuder** [comment]
I will update license shortly.

**Comment by pasuder** [comment]
Added in cfbc4a16
